# Generated by Django 6.0.4 on 2026-05-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_ride_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
